// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6pZYhqtjNbGq3CgGIICoOcyA1rLwPmAs',
    appId: '1:11941350256:web:aaf5e86fe135736dde1db5',
    messagingSenderId: '11941350256',
    projectId: 'chatty-96dce',
    authDomain: 'chatty-96dce.firebaseapp.com',
    storageBucket: 'chatty-96dce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmwBQokbc3lgE9ajM8uf0xpVkleobxxno',
    appId: '1:11941350256:android:d6c75283884db989de1db5',
    messagingSenderId: '11941350256',
    projectId: 'chatty-96dce',
    storageBucket: 'chatty-96dce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp2i_9VsYJjJozmxe0rZTaQmvte1xouEM',
    appId: '1:11941350256:ios:38e2e502c4e6ebe7de1db5',
    messagingSenderId: '11941350256',
    projectId: 'chatty-96dce',
    storageBucket: 'chatty-96dce.appspot.com',
    iosClientId:
        '11941350256-p7ei9m5uc5nc752gnmp82khua9degooh.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp2i_9VsYJjJozmxe0rZTaQmvte1xouEM',
    appId: '1:11941350256:ios:38e2e502c4e6ebe7de1db5',
    messagingSenderId: '11941350256',
    projectId: 'chatty-96dce',
    storageBucket: 'chatty-96dce.appspot.com',
    iosClientId:
        '11941350256-p7ei9m5uc5nc752gnmp82khua9degooh.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatty',
  );
}
